---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  # - name: debian-8.2
  - name: centos-6.7

suites:
  - name: plm_website
    data_bags_path: "test/integration/data_bags"
    run_list:
        - recipe[plm-haproxy::plm_website]
    attributes:
        haproxy:
            servers:
                - name: 'first'
                  ip: '10.0.0.1'
                  port: 80
                  maxconn: 20
                  weight: 50

                - name: 'second'
                  ip: '10.0.0.2'
                  port: 80
                  maxconn: 20
                  weight: 50
